version: '3.8'

services:
  web:
    image: registry.diikstra.fr/potblog:latest
    ports:
      - "10080:8080"
    environment:
      - ENV=prod
      - PORT=8080
    restart: unless-stopped
    volumes:
      - potblog_db:/app/potblog.db

volumes:
  potblog_db: